image: ubuntu

branches:
  only:
    - master
    - /feature.*/

services:
  - docker

build_script:
  - docker build --tag gusztavvargadr/hello-world:appveyor-latest ./src

test_script:
  - docker run gusztavvargadr/hello-world:appveyor-latest

deploy_script:
  - docker push gusztavvargadr/hello-world:appveyor-latest
