trigger:
- master
- feature*/*

pr: none

pool:
  vmImage: 'ubuntu-16.04'

variables:
- group: docker-credentials
- name: docker-image-name
  value: '$(docker-username)/hello-world'
- name: docker-image-tag
  value: 'azp-$(Build.BuildNumber)'

steps:
- script: set
  displayName: 'Variable Diagnostics'

- script: docker login --username $(docker-username) --password $DOCKER_PASSWORD $(docker-registry)
  displayName: 'Init'
  env:
    DOCKER_PASSWORD: $(docker-password)

- script: docker build --tag build src
  displayName: 'Build'

- script: docker run --rm build
  displayName: 'Test'

- script: docker tag build $(docker-registry)$(docker-image-name):$(docker-image-tag)
  displayName: 'Package'

- script: docker push $(docker-registry)$(docker-image-name):$(docker-image-tag)
  displayName: 'Publish'
