trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: ci
  displayName: CI

  jobs:
  - template: build/azure-pipelines.ci.yml
    parameters:
      name: Linux
      vmImage: ubuntu-16.04
      configuration: amd64

  - template: build/azure-pipelines.ci.yml
    parameters:
      name: Linux
      vmImage: windows-2019
      configuration: windows-amd64

- stage: cd
  displayName: CD

  jobs:
  - template: build/azure-pipelines.cd.yml
    parameters:
      name: Linux
      vmImage: ubuntu-16.04
      configuration: amd64

  - template: build/azure-pipelines.cd.yml
    parameters:
      name: Linux
      vmImage: windows-2019
      configuration: windows-amd64
