trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: build
  displayName: Build

  jobs:
  - template: build/azure-pipelines.build.yml
    parameters:
      configurations:
        - os: linux
          arch: amd64
        - os: windows
          arch: amd64

- stage: deployLocalhost
  displayName: Deploy - localhost
  variables:
  - group: environment-localhost
  
  jobs:
  - template: build/azure-pipelines.deploy.yml
    parameters:
      configurations:
        - os: linux
          arch: amd64
        - os: windows
          arch: amd64
      dockerRegistryServiceConnection: ''

- stage: deployDockerIo
  displayName: Deploy - docker.io
  variables:
  - group: environment-dockerio

  jobs:
  - template: build/azure-pipelines.deploy.yml
    parameters:
      configurations:
        - os: linux
          arch: amd64
        - os: windows
          arch: amd64
      dockerRegistryServiceConnection: docker-registry-dockerio
