trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: ci
  displayName: ci

  jobs:
  - job: build
    displayName: Build
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
    - template: azure-pipelines.ci.build.yml

- stage: cd
  displayName: CD

  jobs:
  - job: deployLocalhost
    displayName: Deploy - Localhost
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
    - group: docker-registry-localhost
    strategy:
      matrix:
        semver:
          package-version: ''
        rc:
          package-version: 'rc'
        latest:
          package-version: 'latest'

    steps:
    - template: azure-pipelines.cd.deploy.yml

  - job: deployDockerHub
    displayName: Deploy - Docker Hub
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
    - group: docker-registry-dockerhub
    dependsOn: deployLocalhost

    steps:
    - template: azure-pipelines.cd.deploy.yml
