trigger:
- master
- feature*/*
- refs/tags/*

pr: none

stages:
- stage: build
  displayName: Build
  variables:
  - group: docker-registry-dockerhub

  jobs:
  - job: publish
    displayName: Publish
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
    - script: |
        dotnet tool install Cake.Tool --global --version 0.33.0
      displayName: Init - .NET Tool Install Cake

    - script: |
        docker login --username $DOCKER_LOGIN_USERNAME --password $DOCKER_LOGIN_PASSWORD $DOCKER_LOGIN_SERVER
      displayName: Init - Docker Login
      env:
        DOCKER_LOGIN_USERNAME: $(docker-registry-username)
        DOCKER_LOGIN_PASSWORD: $(docker-registry-password)
        DOCKER_LOGIN_SERVER: $(docker-registry-server)

    - script: |
        ~/.dotnet/tools/dotnet-cake build.cake --target=publish
      displayName: Publish

    - task: ArchiveFiles@2
      displayName: Artifacts - Archive - Source
      inputs:
        rootFolderOrFile: $(Build.SourcesDirectory)
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/source.zip'

    - task: PublishPipelineArtifact@0
      displayName: Artifacts - Publish
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: build-publish

- stage: deploy
  displayName: Deploy
  variables:
  - group: docker-registry-dockerhub
  dependsOn: build

  jobs:
  - deployment: publish
    displayName: Publish
    pool:
      vmImage: 'ubuntu-16.04'
    environment: Default

    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              ls -Ral ..

          - checkout: self

          - script: |
              dotnet tool install Cake.Tool --global --version 0.33.0
            displayName: Init - .NET Tool Install Cake

          - script: |
              docker login --username $DOCKER_LOGIN_USERNAME --password $DOCKER_LOGIN_PASSWORD $DOCKER_LOGIN_SERVER
            displayName: Init - Docker Login
            env:
              DOCKER_LOGIN_USERNAME: $(docker-registry-username)
              DOCKER_LOGIN_PASSWORD: $(docker-registry-password)
              DOCKER_LOGIN_SERVER: $(docker-registry-server)

          - script: |
              ~/.dotnet/tools/dotnet-cake build.cake --target=restore
            displayName: Build
