trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: ci
  displayName: ci

  jobs:
  - job: build
    displayName: Build
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
    - template: azure-pipelines.ci.build.yml

- stage: cd
  displayName: CD
  dependsOn: ci

  jobs:
  - job: deployDockerHub
    displayName: Deploy - Docker Hub
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
    - group: docker-registry-dockerhub

    steps:
    - template: azure-pipelines.cd.deploy.yml
      parameters:
        dockerRegistryServer: $(docker-registry-server)
        docker-registry-username: $(docker-registry-username)
        docker-registry-password: $(docker-registry-password)
