trigger:
- master
- feature*/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker build -t build src
  displayName: 'Docker Build'

- script: docker run --rm build
  displayName: 'Docker Run'
