trigger:
- master
- feature*/*

pr: none

pool:
  vmImage: 'ubuntu-16.04'

variables:
- group: docker-registry-dockerhub
- name: docker-image-name
  value: '$(docker-registry-username)/hello-world'
- name: docker-image-tag
  value: 'azp-$(Build.BuildNumber)'
- name: docker-image-ref
  value: '$(docker-registry-address)$(docker-image-name):$(docker-image-tag)'

steps:
- script: docker login --username $(docker-registry-username) --password $DOCKER_REGISTRY_PASSWORD $(docker-registry-address)
  displayName: 'Init'
  env:
    DOCKER_REGISTRY_PASSWORD: $(docker-registry-password)

- script: docker build --tag build src
  displayName: 'Build'

- script: docker run build
  displayName: 'Test'

- script: docker tag build $(docker-image-ref)
  displayName: 'Package'

- script: docker push $(docker-image-ref)
  displayName: 'Publish'
