trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: ci
  displayName: CI

  jobs:
  - template: build/azure-pipelines.ci.build.yml
    parameters:
      vmImage: ubuntu-16.04
      configuration: amd64

- stage: cd
  displayName: CD

  jobs:
  - job: deployLocalhost
    displayName: Deploy - localhost
    pool:
      vmImage: ubuntu-16.04
    variables:
    - group: docker-registry-localhost

    steps:
    - template: build/azure-pipelines.cd.deploy.yml

  - job: deployDockerIo
    displayName: Deploy - docker.io
    pool:
      vmImage: ubuntu-16.04
    variables:
    - group: docker-registry-dockerio
    dependsOn: deployLocalhost

    steps:
    - template: build/azure-pipelines.cd.deploy.yml
