trigger:
- master
- feature*/*
- refs/tags/*

pr: none

pool:
  vmImage: 'ubuntu-16.04'

variables:
- group: docker-registry-dockerhub
- name: docker-image-name
  value: '$(docker-registry-address)$(docker-registry-username)/hello-world'

steps:
- script: docker login --username $(docker-registry-username) --password $DOCKER_REGISTRY_PASSWORD $(docker-registry-address)
  displayName: 'Init'
  env:
    DOCKER_REGISTRY_PASSWORD: $(docker-registry-password)

- script: docker build --tag build src
  displayName: 'Build'

- script: docker run build
  displayName: 'Test'

- script: |
    docker tag build $(docker-image-name):azp-$(Build.BuildNumber)
    docker push $(docker-image-name):azp-$(Build.BuildNumber)
  displayName: 'Publish for build number'

- script: |
    docker tag build $(docker-image-name):branch-$(Build.SourceBranchName)-latest
    docker push $(docker-image-name):branch-$(Build.SourceBranchName)-latest
  displayName: 'Publish for branch latest'

- script: |
    docker tag build $(docker-image-name):ci-latest
    docker push $(docker-image-name):ci-latest
  displayName: 'Publish for CI latest'
