trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: ci
  displayName: ci

  jobs:
  - job: build
    displayName: Build
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
    - template: azure-pipelines.ci.yml

- stage: cd
  displayName: CD
  variables:
  - group: docker-registry-dockerhub
  dependsOn: ci

  jobs:
  - job: deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
    - template: azure-pipelines.cd.deploy.yml
      parameters:
        docker-registry-server-p: $(docker-registry-server)
        docker-registry-username-p: $(docker-registry-username)
        docker-registry-password-p: $(docker-registry-password)
