trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'
pr: none

stages:
  - template: ./build/azp/azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: [ 'linux', 'amd64' ]
        - name: [ 'windows', 'amd64' ]
        - name: [ 'manifest' ]
          dependsOn:
            - [ 'linux', 'amd64' ]
            - [ 'windows', 'amd64' ]
