trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: stageCi
  displayName: CI

  jobs:
  - job: jobBuild
    displayName: Build
    pool:
      vmImage: ubuntu-16.04

    steps:
    - template: build/azure-pipelines.ci.build.yml

- stage: stageCd
  displayName: CD

  jobs:
  - job: jobDeployLocalhost
    displayName: Deploy - localhost
    pool:
      vmImage: ubuntu-16.04
    variables:
    - group: docker-registry-localhost
    strategy:
      matrix:
        semver:
          docker-image-tag: ''
        rc:
          docker-image-tag: rc
        # latest:
        #   docker-image-tag: latest

    steps:
    - template: build/azure-pipelines.cd.deploy.yml

  - job: jobDeployDockerIo
    displayName: Deploy - docker.io
    pool:
      vmImage: ubuntu-16.04
    variables:
    - group: docker-registry-dockerio
    strategy:
      matrix:
        semver:
          docker-image-tag: ''
        rc:
          docker-image-tag: rc
        # latest:
        #   docker-image-tag: latest
    dependsOn: jobDeployLocalhost

    steps:
    - template: build/azure-pipelines.cd.deploy.yml
