trigger:
- master
- feature*/*
- refs/tags/*

pr: none

pool:
  vmImage: 'ubuntu-16.04'

variables:
- group: docker-registry-dockerhub
- name: docker-image-name
  value: '$(docker-registry-address)$(docker-registry-username)/hello-world'

steps:
- script: |
    dotnet tool install Cake.Tool --global --version 0.33.0
  displayName: 'Init - .NET Tool Install Cake'

- script: docker login --username $(docker-registry-username) --password $DOCKER_REGISTRY_PASSWORD $(docker-registry-address)
  displayName: 'Init - Docker Login'
  env:
    DOCKER_REGISTRY_PASSWORD: $(docker-registry-password)

- script: |
    ~/.dotnet/tools/dotnet-cake build.cake --target=publish --app-version=ci-azp-$(Build.BuildNumber)
  displayName: 'Build'
