trigger:
- master
- feature*/*

pr: none

pool:
  vmImage: 'ubuntu-16.04'

variables:
- group: docker-registry-dockerhub
- name: registry-address
  value: $(docker-registry-address)
- name: registry-username
  value: $(docker-registry-username)
- name: registry-password
  value: $(docker-registry-password)
- name: registry-secret
  value: $(docker-registry-secret)
- name: image-name
  value: '$(docker-registry-username)/hello-world'
- name: image-tag
  value: 'azp-$(Build.BuildNumber)'
- name: image-ref
  value: '$(registry-address)$(image-name):$(image-tag)'

steps:
- script: set
  displayName: 'Variables Diagnostics'
  env:
    REGISTRY_SECRET: $(registry-secret)

- script: docker login --username $(registry-username) --password $REGISTRY_PASSWORD $(registry-address)
  displayName: 'Init'
  env:
    REGISTRY_PASSWORD: $(registry-password)

- script: docker build --tag build src
  displayName: 'Build'

- script: docker run --rm build
  displayName: 'Test'

- script: docker tag build $(image-ref)
  displayName: 'Package'

- script: docker push $(image-ref)
  displayName: 'Publish'
