trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: build
  displayName: Build

  jobs:
  - template: build/azure-pipelines.build.yml
    parameters:
      configurations:
        - name: amd64
          job: Linux
          vmImage: ubuntu-16.04
        - name: windows-amd64
          job: Windows
          vmImage: windows-2019

- stage: deployLocalhost
  displayName: Deploy - localhost
  variables:
  - group: docker-registry-localhost
  
  jobs:
  - template: build/azure-pipelines.deploy.yml
    parameters:
      configurations:
        - name: amd64
          job: Linux
          vmImage: ubuntu-16.04
        - name: windows-amd64
          job: Windows
          vmImage: windows-2019
      dockerRegistryServiceConnection: ''

- stage: deployDockerIo
  displayName: Deploy - docker.io
  variables:
  - group: docker-registry-dockerio

  jobs:
  - template: build/azure-pipelines.deploy.yml
    parameters:
      configurations:
        - name: amd64
          job: Linux
          vmImage: ubuntu-16.04
        - name: windows-amd64
          job: Windows
          vmImage: windows-2019
      dockerRegistryServiceConnection: docker-registry-dockerio
