trigger:
- master
- feature*/*

pr: none

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: docker build -t build src
  displayName: 'Docker Build'

- script: docker run --rm build
  displayName: 'Docker Run'
