trigger:
- master
- feature/*
- hotfix/*
- refs/tags/*

pr: none

stages:
- stage: build
  displayName: Build

  jobs:
  - template: build/azure-pipelines.build.yml
    parameters:
      name: Linux
      displayName: amd64
      vmImage: ubuntu-16.04
      configuration: amd64

  - template: build/azure-pipelines.build.yml
    parameters:
      name: Windows
      displayName: windows-amd64
      vmImage: windows-2019
      configuration: windows-amd64

- stage: deployLocalhost
  displayName: Deploy - localhost
  variables:
  - group: docker-registry-localhost
  
  jobs:
  - template: build/azure-pipelines.deploy.yml
    parameters:
      name: LinuxLocalhost
      displayName: amd64 localhost
      vmImage: ubuntu-16.04
      configuration: amd64
      dockerRegistryServiceConnection: ''

  - template: build/azure-pipelines.deploy.yml
    parameters:
      name: WindowsLocalhost
      displayName: windows-amd64 localhost
      vmImage: windows-2019
      configuration: windows-amd64
      dockerRegistryServiceConnection: ''

- stage: deployDockerIo
  displayName: Deploy - docker.io
  variables:
  - group: docker-registry-dockerio

  jobs:
  - template: build/azure-pipelines.deploy.yml
    parameters:
      name: LinuxDockerIo
      displayName: amd64 dockerio
      vmImage: ubuntu-16.04
      configuration: amd64
      dockerRegistryServiceConnection: docker-registry-dockerio

  - template: build/azure-pipelines.deploy.yml
    parameters:
      name: WindowsDockerIo
      displayName: windows-amd64 dockerio
      vmImage: windows-2019
      configuration: windows-amd64
      dockerRegistryServiceConnection: docker-registry-dockerio
