version: '3'

services:
  gitversion:
    image: gittools/gitversion-dotnetcore:linux-4.0.1
    volumes:
      - .:/data
    command:
      - /data
      - /l
      - console
      - /showvariable
      - SemVer
  app:
    build: src
    image: ${APP_IMAGE_REGISTRY}${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
